Rearranged root/store/

diff --git a/apps/root/store/15 b/apps/root/store/15
--- a/apps/root/store/15
+++ b/apps/root/store/15
@@ -1,31 +1,21 @@
-#@ Sum, Avg, Grade of 3 Subjects
+#@ Maximum of Three
 
-echo -n "Enter marks of Subject 1 : "
-read s1
-echo -n "Enter marks of Subject 2 : "
-read s2
-echo -n "Enter marks of Subject 3 : "
-read s3
+echo -n "Enter first number  : "
+read a
+echo -n "Enter second number : "
+read b
+echo -n "Enter third number  : "
+read c
 
-sum=$(expr $s1 + $s2 + $s3)
-avg=$(expr $sum / 3)
-
-if [ $avg -ge 90 ]; then
-    grade="O"
-elif [ $avg -ge 80 ]; then
-    grade="E"
-elif [ $avg -ge 70 ]; then
-    grade="A"
-elif [ $avg -ge 60 ]; then
-    grade="B"
-elif [ $avg -ge 50 ]; then
-    grade="C"
-elif [ $avg -ge 40 ]; then
-    grade="D"
-else
-    grade="F"
+if [ $a -eq $b ] && [ $b -eq $c ] || [ $c -eq $a ]; then
+    echo "Error : Values must not be same"
+    exit 1
 fi
 
-echo "Total Marks: $sum"
-echo "Average Marks: $avg"
-echo "Grade: $grade"
+if [ $a -gt $b ] && [ $a -gt $c ]; then
+    echo "Maximum value is $a"
+elif [ $b -gt $c ]; then
+    echo "Maximum value is $b"
+else
+    echo "Maximum value is $c"
+fi
